from typing import Protocol


class IPresetManager(Protocol):
    def save_preset(self, excluded_headings_indices: list[int], preset_name: str): ...
    def get_preset(self, preset_name: str) -> list[int]: ...
    def get_all_presets(self) -> dict[str, list[int]]: ...
