from typing import Protocol


class IApi(Protocol):
    def get_indexed_headings(self, source_path: str) -> dict[int, str]: ...
    def export(
        self,
        source_path: str,
        destination_path: str,
        excluded_heading_indices: list[int],
    ): ...
    def save_preset(self, excluded_headings_indices: list[int], preset_name: str): ...
    def get_preset(self, preset_name: str) -> list[int]: ...
    def get_all_presets(self) -> dict[str, list[int]]: ...
